### PR TITLE
Hyperlink opening in same tab fix

### PR DESCRIPTION
**Pull request by tejas-k3**
Fix for issue #9

### CODE REVIEW

**Comment by siddhi-gh** [comment]
- Having few words the the description about what has been changed gives the reviewer a better understanding of what to look out for while reviewing the PR.
- The PR description may include an evidence in the form of a screenshot/screen recording indicating the impact of your changes in the website.
- A set of instructions to test the changes made in the PR is always appreciated.

**Comment by tejas-k3** [comment]
Noted, it's a single link change with issue link attached hence didn't include!

Fix :- Changed a element tag to open hyperlinks in new tab

**Comment by tejas-k3** [comment]
Preview of functional changes
https://github.com/tejas-k3/tejas-kothari-portfolio/assets/77725958/71e77a4f-7d93-4b67-9619-41fe774c0a89

**Review by siddhi-gh — APPROVED** [review]
Changes work as expected. Approved.

https://github.com/tejas-k3/tejas-kothari-portfolio/assets/91131867/7bb2b550-894a-4979-9481-00565992c249

**Pull request merged**
